name: Code Quality Check

on: pull_request
permissions:
 security-events: write

jobs:
  ej_2:
    runs-on: ubuntu-latest

    steps:
      - name: Python Linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
